# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Leading NA
#'
#' This function returns a logical vector identifying if
#' there are leading NA, marking the leadings NA as TRUE and
#' everything else as FALSE.
#'
#' @param x An integer vector
#' @export
goc <- function(n_in, l_h, n_h, n_out, Ws, Fin, t_eps, t_steps) {
    .Call(`_snnLearn_goc`, n_in, l_h, n_h, n_out, Ws, Fin, t_eps, t_steps)
}

rcpp_hello_world <- function() {
    .Call(`_snnLearn_rcpp_hello_world`)
}

