# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Solve the LIF forward problem
#'
#' Integrate a feedforward Linear Leaky Integrate and Fire Network via forward Euler.
#'
#' @param n_in The number of input neurons, a scalar integer.
#' @param l_h The number of hidden layers, a scalar integer.
#' @param n_h The number of hidden neurons in each layer (of length l_h).
#' @param n_out The number of output neurons, a scalar integer, for now has to be 1.
#' @param Ws A list of matrices giving the weights between layers, of length 1 fewer than the number of layers. The first matrix is of dimension n_in x n_h[1], etc.
#' @param Fin A list of numeric vectors, giving the times of the input spikes.
#' @param t_eps A scalar double, the step size for numerical integration.
#' @param t_steps A scalar integer, the number of finite difference iterations.
#' @return A list of lists of numeric vectors. The first entry will be Fin, and so on.
#' @export
goc <- function(n_in, l_h, n_h, n_out, Ws, Fin, t_eps, t_steps) {
    .Call(`_snnLearn_goc`, n_in, l_h, n_h, n_out, Ws, Fin, t_eps, t_steps)
}

